apiVersion: v1
kind: Namespace
metadata:
  name: study-ai
  labels:
    name: study-ai
    app: study-ai-platform
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: study-ai-config
  namespace: study-ai
data:
  DATABASE_URL: "mongodb://mongodb-service:27017/study_ai"
  ENVIRONMENT: "production"
  DEBUG: "false"
  NEXT_PUBLIC_API_URL: "http://backend-service:8000"
  NEXT_PUBLIC_ENVIRONMENT: "production"
---
apiVersion: v1
kind: Secret
metadata:
  name: study-ai-secrets
  namespace: study-ai
type: Opaque
data:
  # Base64 encoded values
  MONGO_ROOT_USERNAME: YWRtaW4=  # admin
  MONGO_ROOT_PASSWORD: cGFzc3dvcmQxMjM=  # password123
  JWT_SECRET: eW91ci1zZWNyZXQta2V5LWhlcmU=  # your-secret-key-here