apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: study-ai
  labels:
    app: frontend
    tier: presentation
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: frontend
      tier: presentation
  template:
    metadata:
      labels:
        app: frontend
        tier: presentation
    spec:
      initContainers:
      - name: wait-for-backend
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          until nc -z backend-service 8000; do
            echo "Waiting for Backend to be ready..."
            sleep 2
          done
          echo "Backend is ready!"
      containers:
      - name: frontend
        image: study-ai-frontend:latest
        imagePullPolicy: IfNotPresent # Change to Always for production
        ports:
        - containerPort: 3000
          name: http
        envFrom:
        - configMapRef:
            name: study-ai-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "125m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: study-ai
  labels:
    app: frontend
    tier: presentation
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: frontend
    tier: presentation
  type: ClusterIP